version: '3.7'

services:
  app:
    build:
      context: .
    container_name: checkout-api
    ports:
      - "9001:9001"
    networks:
      - microservice
    volumes:
      - .:/app

  grpc-service:
    build:
      context: docker/service-grpc
    container_name: grpc-service
    ports:
      - "50051:50051"
    networks:
      - microservice


networks:
  microservice:
    driver: bridge
